# H2 DB 설정
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

# JPA 설정
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true


  mvc:
    hiddenmethod:
      filter:
        enabled: true

# logging
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG



